# Generated by Django 4.1.1 on 2022-09-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippindAddress',
            new_name='ShippingAddress',
        ),
    ]
